services:
  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: greenops
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ ping: 1 }).ok' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - greenops-net

  green-workload:
    build:
      context: ./workload
    restart: unless-stopped
    environment:
      WORKLOAD_PORT: 5000
      ENVIRONMENT: docker
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:5000/health')\""]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - greenops-net

  greenops-api:
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
      green-workload:
        condition: service_healthy
    environment:
      BACKEND_HOST: 0.0.0.0
      BACKEND_PORT: 8000
      DEBUG: "false"

      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB_NAME: greenops

      K8S_NAMESPACE: greenops
      WORKLOAD_DEPLOYMENT_NAME: green-workload
      MIN_REPLICAS: 0
      MAX_REPLICAS: 5

      SCALE_UP_CPU_THRESHOLD: 65
      SCALE_DOWN_CPU_THRESHOLD: 25
      TARGET_RPS_PER_POD: 20
      IDLE_SCALE_TO_ZERO_SECONDS: 60
      SCALE_UP_COOLDOWN_SECONDS: 10
      SCALE_DOWN_COOLDOWN_SECONDS: 60
      AUTOSCALER_INTERVAL: 10

      P_IDLE_WATTS: 35
      P_MAX_WATTS: 90
      CARBON_FACTOR_KG_PER_KWH: 0.708
      ELECTRICITY_COST_PER_KWH: 8

      PROMETHEUS_URL: http://prometheus:9090
      GATEWAY_URL: http://traffic-gateway:5001
      WORKLOAD_URL: http://green-workload:5000
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health')\""]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - greenops-net

  traffic-gateway:
    build:
      context: ./gateway
    restart: unless-stopped
    depends_on:
      greenops-api:
        condition: service_healthy
      green-workload:
        condition: service_healthy
    environment:
      GATEWAY_PORT: 5001
      WORKLOAD_URL: http://green-workload:5000
      BACKEND_URL: http://greenops-api:8000
    ports:
      - "5001:5001"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:5001/health')\""]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - greenops-net

volumes:
  mongo_data:

networks:
  greenops-net:
    driver: bridge
